In [ ]:
print('hello')

hello


In [ ]:
a = 2
a

2

In [ ]:
a = 2
b = 3
print('a = '+str(a)+' and '+'b = '+str(b))

a = 2 and b = 3


In [ ]:
type(a)

int

In [ ]:
s1 = 'RJ college'
type(s1)

str

In [ ]:
f=2.34546796547
type(f)

float

In [ ]:
a=[1,2,3]
a

[1, 2, 3]

In [ ]:
type(a)

list

In [ ]:
b=[4,5,6]
b

[4, 5, 6]

In [ ]:
c = []
for i in range(len(a)):
  c.append(a[i]*b[i])
c

[4, 10, 18]

In [ ]:
c = []
for i in range(len(a)):
  c.append(a[i]+b[i])
c

[5, 7, 9]

In [ ]:
import time
print('sleeping')
time.sleep(30)
print('done sleeping')

sleeping
done sleeping


In [ ]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.ndim

2

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.dtype.name

'int64'

In [ ]:
a.itemsize

8

In [ ]:
a.size

15

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b=np.array([[11,13,14],[56,57,58]])
b

array([[11, 13, 14],
       [56, 57, 58]])

In [ ]:
b.reshape(3,2)
b

array([[11, 13, 14],
       [56, 57, 58]])

In [ ]:
c=b.reshape(3,2)
c

array([[11, 13],
       [14, 56],
       [57, 58]])

In [ ]:
d=np.array([['a','b','c','d','e'],['f','g','h','i','j']])
d

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')

In [ ]:
e=d.reshape(2,5)
e

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')